title: DataBase Design - online rental company
logo: /assets/CV.jpg
description: It is the project about SQL DataBase Design during my postgraduate study.
show_downloads: false
theme: jekyll-theme-architect
github:
  is_project_page: false
